[package]
name = "moksha-wallet"
version = "0.2.0-beta"
edition = "2021"
resolver = "2"
repository = "https://github.com/ngutech21/moksha"
license = "MIT"
description = "cashu-wallet library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "moksha_wallet"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
secp256k1 = { version = "0.28.1", features = ["serde"] }
moksha-core = { version = "0.2.0-beta", path = "../moksha-core" }
serde_json = "1.0.108"
serde = "1.0.193"
rand = "0.8.5"
thiserror = "1.0.50"
async-trait = "0.1.74"
lightning-invoice = "0.27.0"
url = "2.4.1"
dirs = "5.0.1"

[target.'cfg(target_family = "wasm")'.dependencies]
gloo-net = { version = "0.4.0" }
serde-wasm-bindgen = "0.6.1"
wasm-bindgen = "0.2.88"

rexie = "0.5.0"
tokio = { version = "1.35.1", features = ["rt", "sync"] }

[target.'cfg(not(target_family="wasm"))'.dependencies]
reqwest = { version = "0.11.23", features = ["serde_json", "json", "rustls-tls"], default-features = false }
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
sqlx = { version = "0.7.3", default-features = false, features = ["sqlite", "runtime-tokio", "tls-native-tls", "migrate", "macros"] }

[dev-dependencies]
tempfile = "3.8.1"
mockall = "0.12.1"
