name: docker-push-dockerhub

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to docker.io
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u '+%F-%T')"

      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            COMMITHASH=${{ steps.date.outputs.sha }}
            BUILDTIME=${{ steps.date.outputs.date }}

          tags: docker.io/${{ secrets.DOCKER_NAME }}/moksha-mint:latest, docker.io/${{ secrets.DOCKER_NAME }}/moksha-mint:${{ steps.date.outputs.sha }}
